### ISSUE TITLE
minor Traceback no Fedora 37

### ISSUE THREAD

**Issue by sergiomb2** [rpm-software-management/mock#1018]
### Short description of the problem
when mock builds fails , it ends with Traceback which I think that can be solved 

```
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.7i1xVJ (%install)
Bad exit status from /var/tmp/rpm-tmp.7i1xVJ (%install)
Child return code was: 1
EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M 6e3be579a2a142b19d998c1d1e71baad -D /var/lib/mock/fedora-37-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.zdlk435y:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007" --setenv=PS1=<mock-chroot> \\s-\\v\\$  --setenv=LANG=C.UTF-8 --setenv=CCACHE_DIR=/var/tmp/ccache --setenv=CCACHE_UMASK=002 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/ocamlfuse.spec\n', 1)]
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
result = func(*args, **kw)
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/mockbuild/util.py", line 598, in do_with_status
raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed:
# /usr/bin/systemd-nspawn -q -M 6e3be579a2a142b19d998c1d1e71baad -D /var/lib/mock/fedora-37-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.zdlk435y:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --setenv=CCACHE_DIR=/var/tmp/ccache --setenv=CCACHE_UMASK=002 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/ocamlfuse.spec
```

### Output of `rpm -q mock`

mock-3.5-1.fc37.noarch

### Steps to reproduce issue

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-conf### Steps to reproduce issue

1.
2.
3.

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

Output of `mock --debug-config`
```
mock --debug-config
INFO: mock.py version 3.5 starting (python version = 3.11.1, NVR = mock-3.5-1.fc37)...
Start(bootstrap): init plugins
INFO: selinux disabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux disabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['additional_packages'] = []
config_opts['backup_on_clean'] = True
config_opts['bootstrap_image'] = 'registry.fedoraproject.org/fedora:rawhide'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @{% if mirrored %}buildsys-{% endif %}build'
config_opts['chrootuid'] = 1000
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['createrepo_on_rpms'] = True
config_opts['description'] = 'Fedora Rawhide'
config_opts['dist'] = 'rawhide'
config_opts['dnf.conf'] = ('\n'
'[main]\n'
'keepcache=1\n'
'debuglevel=2\n'
'reposdir=/dev/null\n'
'logfile=/var/log/yum.log\n'
'retries=20\n'
'obsoletes=1\n'
'gpgcheck=0\n'
'assumeyes=1\n'
'syslog_ident=mock\n'
'syslog_device=\n'
'install_weak_deps=0\n'
'metadata_expire=0\n'
'best=1\n'
'module_platform_id=platform:f{{ releasever }}\n'
'protected_packages=\n'
'user_agent={{ user_agent }}\n'
'\n'
'{%- macro rawhide_gpg_keys() -%}\n'
'file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
'{%- for version in [releasever|int, releasever|int - 1]\n'
'%} file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
'version }}-primary\n'
'{%- endfor %}\n'
'{%- endmacro %}\n'
'\n'
'# repos\n'
'\n'
'[local]\n'
'name=local\n'
'baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/$basearch/\n'
'cost=2000\n'
'enabled={{ not mirrored }}\n'
'skip_if_unavailable=False\n'
'\n'
'[local-source]\n'
'name=local-source\n'
'baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/src/\n'
'cost=2000\n'
'enabled=0\n'
'skip_if_unavailable=False\n'
'\n'
'{% if mirrored %}\n'
'[fedora]\n'
'name=fedora\n'
'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=$basearch\n'
'gpgkey={{ rawhide_gpg_keys() }}\n'
'gpgcheck=1\n'
'skip_if_unavailable=False\n'
'\n'
'[fedora-debuginfo]\n'
'name=Fedora Rawhide - Debug\n'
'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-debug&arch=$basearch\n'
'enabled=0\n'
'gpgkey={{ rawhide_gpg_keys() }}\n'
'gpgcheck=1\n'
'skip_if_unavailable=False\n'
'\n'
'[fedora-source]\n'
'name=fedora-source\n'
'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-source&arch=$basearch\n'
'gpgkey={{ rawhide_gpg_keys() }}\n'
'gpgcheck=1\n'
'enabled=0\n'
'skip_if_unavailable=False\n'
'\n'
'# modular\n'
'\n'
'[rawhide-modular]\n'
'name=Fedora - Modular Rawhide - Developmental packages for the next Fedora '
'release\n'
'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-modular&arch=$basearch\n'
'# if you want to enable it, you should set best=0\n'
'# see https://bugzilla.redhat.com/show_bug.cgi?id=1673851\n'
'enabled=0\n'
'gpgcheck=1\n'
'gpgkey={{ rawhide_gpg_keys() }}\n'
'skip_if_unavailable=False\n'
'\n'
'[rawhide-modular-debuginfo]\n'
'name=Fedora - Modular Rawhide - Debug\n'
'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-modular-debug&arch=$basearch\n'
'enabled=0\n'
'gpgcheck=1\n'
'gpgkey={{ rawhide_gpg_keys() }}\n'
'skip_if_unavailable=False\n'
'\n'
'[rawhide-modular-source]\n'
'name=Fedora - Modular Rawhide - Source\n'
'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-modular-source&arch=$basearch\n'
'enabled=0\n'
'gpgcheck=1\n'
'gpgkey={{ rawhide_gpg_keys() }}\n'
'skip_if_unavailable=False\n'
'{% endif %}\n')
config_opts['dnf_common_opts'] = ['--setopt=deltarpm=False',
'--setopt=max_parallel_downloads=10',
'--setopt=metadata_expire=259200s']
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
'::1       localhost localhost.localdomain localhost6 '
'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'localhost.localdomain',
'%_platform_multiplier': 1,
'%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
'%_topdir': '/builddir/build'}
config_opts['mirrored'] = True
config_opts['no-config'] = {'epel-8': {'alternatives': {'alma+epel-8': {'description': ['Builds against '
'AlmaLinux 8 '
'repositories, '
'together with '
'the official '
'EPEL '
'repositories.',
'Project page: '
'https://almalinux.org/']},
'centos-stream+epel-8': {'description': ['Builds '
'against '
'CentOS '
'Stream '
'8 '
'repositories '
'(some '
'packages '
'may be '
'a bit '
'ahead '
'the Red '
'Hat '
'Enterprise '
'Linux '
'8) '
'together '
'with '
'the '
'official '
'EPEL 8 '
'repositories.',
'Project '
'page: '
'https://www.centos.org/centos-stream/']},
'circlelinux+epel-8': {'description': ['Builds '
'against '
'Circle '
'Linux 8 '
'repositories, '
'together '
'with the '
'official '
'EPEL '
'repositories.',
'Project '
'page: '
'https://cclinux.org/']},
'rhel+epel-8': {'description': ['Builds against '
'Red Hat '
'Enterprise Linux '
'8 repositories, '
'together with '
'the official '
'EPEL '
'repositories.',
'This mimics what '
'is done in the '
'official EPEL '
'build system, '
'but you need a '
'Red Hat '
'subscription:',
'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
'rocky+epel-8': {'description': ['Builds against '
'Rocky Linux 8 '
'repositories, '
'together with '
'the official '
'EPEL '
'repositories.',
'Project page: '
'https://rockylinux.org/']}}},
'epel-9': {'alternatives': {'alma+epel-9': {'description': ['Builds against '
'AlmaLinux 9 '
'repositories, '
'together with '
'the official '
'EPEL '
'repositories.',
'Project page: '
'https://almalinux.org/']},
'centos-stream+epel-9': {'description': ['Builds '
'against '
'CentOS '
'Stream '
'9 '
'repositories '
'(some '
'packages '
'may be '
'a bit '
'ahead '
'the Red '
'Hat '
'Enterprise '
'Linux '
'9) '
'together '
'with '
'the '
'official '
'EPEL '
'repositories.',
'Project '
'page: '
'https://www.centos.org/centos-stream/']},
'rhel+epel-9': {'description': ['Builds against '
'Red Hat '
'Enterprise Linux '
'9 repositories, '
'together with '
'the official '
'EPEL '
'repositories.',
'This mimics what '
'is done in the '
'official EPEL '
'build system, '
'but you need a '
'Red Hat '
'subscription:',
'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
'rocky+epel-9': {'description': ['Builds against '
'Rocky Linux 9 '
'repositories, '
'together with '
'the official '
'EPEL '
'repositories.',
'Project page: '
'https://rockylinux.org/']}}}}
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
'--bind=/tmp/mock-resolv.2g1c_obv:/etc/resolv.conf',
'--bind=/dev/btrfs-control',
'--bind=/dev/mapper/control',
'--bind=/dev/loop-control',
'--bind=/dev/loop0',
'--bind=/dev/loop1',
'--bind=/dev/loop2',
'--bind=/dev/loop3',
'--bind=/dev/loop4',
'--bind=/dev/loop5',
'--bind=/dev/loop6',
'--bind=/dev/loop7',
'--bind=/dev/loop8',
'--bind=/dev/loop9',
'--bind=/dev/loop10',
'--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
'bind_mount_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'create_dirs': False,
'dirs': [],
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'ccache_enable': True,
'ccache_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'compress': None,
'dir': '/var/cache/mock/fedora-rawhide-x86_64/ccache/u1000/',
'max_cache_size': '20G',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'chroot_scan_enable': False,
'chroot_scan_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'only_failed': True,
'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'compress_logs_enable': False,
'compress_logs_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'command': 'gzip',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'hw_info_enable': True,
'hw_info_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'lvm_root_enable': False,
'lvm_root_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'pool_name': 'mockbuild',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'mount_enable': True,
'mount_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'dirs': [],
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'overlayfs_enable': False,
'overlayfs_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'package_state_enable': True,
'package_state_opts': {'available_pkgs': False,
'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'installed_pkgs': True,
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'pm_request_enable': False,
'pm_request_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'procenv_enable': False,
'procenv_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'root_cache_enable': True,
'root_cache_opts': {'age_check': True,
'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'compress_program': 'pigz',
'decompress_program': None,
'dir': '/var/cache/mock/fedora-rawhide-x86_64/root_cache/',
'exclude_dirs': ['./proc',
'./sys',
'./dev',
'./tmp/ccache',
'./var/cache/yum',
'./var/cache/dnf',
'./var/log'],
'extension': '.gz',
'max_age_days': 15,
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'rpkg_preprocessor_enable': False,
'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
'--output %(target_spec)s',
'requires': ['preproc-rpmspec'],
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'selinux_enable': True,
'selinux_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'showrc_enable': False,
'showrc_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'sign_enable': False,
'sign_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'cmd': 'rpmsign',
'opts': '--addsign %(rpms)s',
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'tmpfs_enable': False,
'tmpfs_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'keep_mounted': False,
'max_fs_size': None,
'mode': '0755',
'required_ram_mb': 900,
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'},
'yum_cache_enable': True,
'yum_cache_opts': {'basedir': '/var/lib/mock/fedora-rawhide-x86_64',
'cache_topdir': '/var/cache/mock',
'cachedir': '/var/cache/mock/fedora-rawhide-x86_64',
'max_age_days': 30,
'max_metadata_age_days': 30,
'online': True,
'resultdir': '/var/lib/mock/fedora-rawhide-x86_64/result',
'root': 'fedora-rawhide-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '38'
config_opts['root'] = 'fedora-rawhide-{{ target_arch }}'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
  ``

**Comment by praiskup** [comment]
Makes sense, thank you for the report!

**Comment by junaruga** [comment]
Any update on this?

**Comment by praiskup** [comment]
No, there's no assignee here - patches are welcome!

**Comment by sergiomb2** [comment]
BTW  we may also clean this message on mock output 
```
Usage: rpmbuild [OPTION...]
DEBUG util.py:445:  Build options with [ <specfile> | <tarball> | <source package> ]:
DEBUG util.py:445:        -bp                        build through %prep (unpack sources and apply
DEBUG util.py:445:                                   patches) from <specfile>
DEBUG util.py:445:        -bf                        build through %conf (%prep, then %conf) from
DEBUG util.py:445:                                   <specfile>
DEBUG util.py:445:        -bc                        build through %build (%prep, %conf, then
DEBUG util.py:445:                                   compile) from <specfile>
DEBUG util.py:445:        -bd                        check build dependencies <specfile>
DEBUG util.py:445:        -bi                        build through %install (%prep, %conf, %build,
DEBUG util.py:445:                                   then install) from <specfile>
DEBUG util.py:445:        -bl                        verify %files section from <specfile>
DEBUG util.py:445:        -ba                        build source and binary packages from
DEBUG util.py:445:                                   <specfile>
DEBUG util.py:445:        -bb                        build binary package only from <specfile>
DEBUG util.py:445:        -bs                        build source package only from <specfile>
DEBUG util.py:445:        -br                        build source package only from <specfile> -
DEBUG util.py:445:                                   calculate dynamic build requires
DEBUG util.py:445:        -rp                        build through %prep (unpack sources and apply
DEBUG util.py:445:                                   patches) from <source package>
DEBUG util.py:445:        -rf                        build through %conf (%prep, then %conf) from
DEBUG util.py:445:                                   <specfile>
DEBUG util.py:445:        -rc                        build through %build (%prep, %conf, then
DEBUG util.py:445:                                   compile) from <source package>
DEBUG util.py:445:        -rd                        check build dependencies <source package>
DEBUG util.py:445:        -ri                        build through %install (%prep, %conf, %build,
DEBUG util.py:445:                                   then install) from <source package>
DEBUG util.py:445:        -rl                        verify %files section from <source package>
DEBUG util.py:445:        -ra                        build source and binary packages from <source
DEBUG util.py:445:                                   package>
DEBUG util.py:445:        -rb                        build binary package only from <source
DEBUG util.py:445:                                   package>
DEBUG util.py:445:        -rs                        build source package only from <source
DEBUG util.py:445:                                   package>
DEBUG util.py:445:        -rr                        build source package only from <source
DEBUG util.py:445:                                   package> - calculate dynamic build requires
DEBUG util.py:445:        -tp                        build through %prep (unpack sources and apply
DEBUG util.py:445:                                   patches) from <tarball>
DEBUG util.py:445:        -tf                        build through %conf (%prep, then %conf) from
DEBUG util.py:445:                                   <specfile>
DEBUG util.py:445:        -tc                        build through %build (%prep, %conf, then
DEBUG util.py:445:                                   compile) from <tarball>
DEBUG util.py:445:        -td                        check build dependencies <tarball>
DEBUG util.py:445:        -ti                        build through %install (%prep, %conf, %build,
DEBUG util.py:445:                                   then install) from <tarball>
DEBUG util.py:445:        -ta                        build source and binary packages from
DEBUG util.py:445:                                   <tarball>
DEBUG util.py:445:        -tb                        build binary package only from <tarball>
DEBUG util.py:445:        -ts                        build source package only from <tarball>
DEBUG util.py:445:        -tr                        build source package only from <tarball> -
DEBUG util.py:445:                                   calculate dynamic build requires
DEBUG util.py:445:        --rebuild                  build binary package from <source package>
DEBUG util.py:445:        --recompile                build through %install (%prep, %build, then
DEBUG util.py:445:                                   install) from <source package>
DEBUG util.py:445:        --buildroot=DIRECTORY      override build root
DEBUG util.py:445:        --build-in-place           run build in current directory
DEBUG util.py:445:        --clean                    remove build tree when done
DEBUG util.py:445:        --nobuild                  do not execute any stages of the build
DEBUG util.py:445:        --nodeps                   do not verify build dependencies
DEBUG util.py:445:        --nodirtokens              generate package header(s) compatible with
DEBUG util.py:445:                                   (legacy) rpm v3 packaging
DEBUG util.py:445:        --noclean                  do not execute %clean stage of the build
DEBUG util.py:445:        --noprep                   do not execute %prep stage of the build
DEBUG util.py:445:        --nocheck                  do not execute %check stage of the build
DEBUG util.py:445:        --rmsource                 remove sources when done
DEBUG util.py:445:        --rmspec                   remove specfile when done
DEBUG util.py:445:        --short-circuit            skip straight to specified stage (only for
DEBUG util.py:445:                                   c,i)
DEBUG util.py:445:        --target=CPU-VENDOR-OS     override target platform
DEBUG util.py:445:  Common options for all rpm modes and executables:
DEBUG util.py:445:    -D, --define='MACRO EXPR'      define MACRO with value EXPR
DEBUG util.py:445:        --undefine=MACRO           undefine MACRO
DEBUG util.py:445:    -E, --eval='EXPR'              print macro expansion of EXPR
DEBUG util.py:445:        --target=CPU-VENDOR-OS     Specify target platform
DEBUG util.py:445:        --macros=<FILE:...>        read <FILE:...> instead of default file(s)
DEBUG util.py:445:        --load=<FILE>              load a single macro file
DEBUG util.py:445:        --noplugins                don't enable any plugins
DEBUG util.py:445:        --nodigest                 don't verify package digest(s)
DEBUG util.py:445:        --nosignature              don't verify package signature(s)
DEBUG util.py:445:        --rcfile=<FILE:...>        read <FILE:...> instead of default file(s)
DEBUG util.py:445:    -r, --root=ROOT                use ROOT as top level directory (default: "/")
DEBUG util.py:445:        --dbpath=DIRECTORY         use database in DIRECTORY
DEBUG util.py:445:        --querytags                display known query tags
DEBUG util.py:445:        --showrc                   display final rpmrc and macro configuration
DEBUG util.py:445:        --quiet                    provide less detailed output
DEBUG util.py:445:    -v, --verbose                  provide more detailed output
DEBUG util.py:445:        --version                  print the version of rpm being used
DEBUG util.py:445:  Options implemented via popt alias/exec:
DEBUG util.py:445:        --with=<option>            enable configure <option> for build
DEBUG util.py:445:        --without=<option>         disable configure <option> for build
DEBUG util.py:445:        --scm=<scm>                shortcut for '--define="__scm <scm>"'
DEBUG util.py:445:        --buildpolicy=<policy>     set buildroot <policy> (e.g. compress man
DEBUG util.py:445:                                   pages)
DEBUG util.py:445:        --trace                    trace macro expansion
DEBUG util.py:445:        --nodebuginfo              do not generate debuginfo for this package
DEBUG util.py:445:  Help options:
DEBUG util.py:445:    -?, --help                     Show this help message
DEBUG util.py:445:        --usage                    Display brief usage message
DEBUG util.py:596:  Child return code was: 0
```

**Comment by praiskup** [comment]
> BTW we may also clean this message on mock output

There's a #999 tracking *that* issue.
