### ISSUE TITLE
epel-6-x86_64 config requires yum on Fedora 26

### ISSUE THREAD

**Issue by subpop** [rpm-software-management/mock#102]
Running the `epel-6-x86_64` config errors with the following:

```
$ mock -r epel-6-x86_64 --init
INFO: mock.py version 1.4.2 starting (python version = 3.6.2)...
Start: init plugins
INFO: selinux enabled
ERROR: No module named 'cli'
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 934, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 703, in main
    buildroot = Buildroot(config_opts, uidManager, state, plugins, bootstrap_buildroot)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/buildroot.py", line 70, in __init__
    self.plugins.init_plugins(self)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugin.py", line 65, in init_plugins
    module.init(self, self.plugin_conf["{0}_opts".format(plugin)], buildroot)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugins/selinux.py", line 27, in init
    SELinux(plugins, conf, buildroot)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugins/selinux.py", line 56, in __init__
    if self._selinuxYumIsSetoptSupported():
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugins/selinux.py", line 111, in _selinuxYumIsSetoptSupported
    import cli
ModuleNotFoundError: No module named 'cli'
```

Tracing through selinux.py, the `cli` module appears to be provided by `/usr/share/yum-cli`, which in turn is provided by the `yum` package on Fedora 26. Installing `yum` does indeed fix this error, but perhaps `selinux.py` could fail more gracefully if `/usr/share/yum-cli` is not found.

**Comment by xsuchy** [comment]
Fixed in commit 1a2acb6
