### ISSUE TITLE
Mageia Cauldron chroots fail with --use-bootstrap-image

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#1111]
```
Start: installing minimal buildroot with dnf
Traceback (most recent call last):
  File "/usr/bin/dnf-3", line 61, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.10/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 32, in <module>
    from dnf.comps import CompsQuery
  File "/usr/lib/python3.10/site-packages/dnf/comps.py", line 27, in <module>
    from dnf.exceptions import CompsError
  File "/usr/lib/python3.10/site-packages/dnf/exceptions.py", line 22, in <module>
    import dnf.util
  File "/usr/lib/python3.10/site-packages/dnf/util.py", line 29, in <module>
    import dnf.callback
  File "/usr/lib/python3.10/site-packages/dnf/callback.py", line 22, in <module>
    import dnf.yum.rpmtrans
  File "/usr/lib/python3.10/site-packages/dnf/yum/rpmtrans.py", line 26, in <module>
    import rpm
  File "/usr/lib64/python3.10/site-packages/rpm/__init__.py", line 38, in <module>
    from rpm._rpm import *
ImportError: /lib64/librpmbuild.so.9: undefined symbol: rpmluavNew
```

**Comment by praiskup** [comment]
> The certificate is expired: The primary key is not live

This issue in particular is fixed by https://github.com/xsuchy/distribution-gpg-keys/pull/99  (bootstrap-installation-from-host failure).  The original problem with outdated cauldron image stays, though.

**Comment by praiskup** [comment]
FTR, the Mageia bootstrap_image we use is non-official;

and it seems stuck on this rather political issue: https://github.com/juanluisbaptiste/docker-brew-mageia/issues/30
