### ISSUE TITLE
Mock 5 broke --install from a clean chroot

### ISSUE THREAD

**Issue by QuLogic** [rpm-software-management/mock#1183]
### Short description of the problem

Using `mock --install` fails because of a missing result directory.

```
$ mock -r fedora-rawhide-x86_64 --install python3-tables
INFO: mock.py version 5.0 starting (python version = 3.11.4, NVR = mock-5.0-1.fc38)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
ERROR: Could not create dir /var/container/mock//fedora-rawhide-x86_64/result. Error: [Errno 13] Permission denied: '/var/container/mock//fedora-rawhide-x86_64/result'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mockbuild/file_util.py", line 22, in mkdirIfAbsent
    os.makedirs(dirName)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/container/mock//fedora-rawhide-x86_64/result'
ERROR:
Could not create output directory for built rpms. The directory specified was:
    /var/container/mock//fedora-rawhide-x86_64/result

Try using the --resultdir= option to select another location. Recommended location is --resultdir=~/mock/.
```

It was not previously necessary to set a `--resultdir` in mock <5, and I don't have any use for one. (Note that I have configured mock to use a different storage path, but this has otherwise been fine before, and works fine with the usual `fedpkg mockbuild`.)

### Output of `rpm -q mock`

mock-5.0-1.fc38.noarch

### Steps to reproduce issue

1. mock -r fedora-rawhide-x86_64 --clean
2. mock -r fedora-rawhide-x86_64 --install python3-tables

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

```
INFO: mock.py version 5.0 starting (python version = 3.11.4, NVR = mock-5.0-1.fc38)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['additional_packages'] = []
config_opts['basedir'] = '/var/container/mock/'
config_opts['bootstrap_image'] = 'registry.fedoraproject.org/fedora:rawhide'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['cache_topdir'] = '/var/container/mock'
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @{% if mirrored %}buildsys-{% endif %}build'
config_opts['chrootuid'] = 1000
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['description'] = 'Fedora Rawhide'
config_opts['dist'] = 'rawhide'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:f{{ releasever }}\n'
 'protected_packages=\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '{%- macro rawhide_gpg_keys() -%}\n'
 'file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 '{%- for version in [releasever|int, releasever|int - 1]\n'
 '%} file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'version }}-primary\n'
 '{%- endfor %}\n'
 '{%- endmacro %}\n'
 '\n'
 '# repos\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/$basearch/\n'
 'cost=2000\n'
 'enabled={{ not mirrored }}\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[local-source]\n'
 'name=local-source\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/src/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '{% if mirrored %}\n'
 '[fedora]\n'
 'name=fedora\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=$basearch\n'
 'gpgkey={{ rawhide_gpg_keys() }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-debuginfo]\n'
 'name=Fedora Rawhide - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-debug&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey={{ rawhide_gpg_keys() }}\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-source]\n'
 'name=fedora-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-source&arch=$basearch\n'
 'gpgkey={{ rawhide_gpg_keys() }}\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '# modular\n'
 '\n'
 '[rawhide-modular]\n'
 'name=Fedora - Modular Rawhide - Developmental packages for the next Fedora '
 'release\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-modular&arch=$basearch\n'
 '# if you want to enable it, you should set best=0\n'
 '# see https://bugzilla.redhat.com/show_bug.cgi?id=1673851\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey={{ rawhide_gpg_keys() }}\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[rawhide-modular-debuginfo]\n'
 'name=Fedora - Modular Rawhide - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-modular-debug&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey={{ rawhide_gpg_keys() }}\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[rawhide-modular-source]\n'
 'name=Fedora - Modular Rawhide - Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=rawhide-modular-source&arch=$basearch\n'
 'enabled=0\n'
 'gpgcheck=1\n'
 'gpgkey={{ rawhide_gpg_keys() }}\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['isolation'] = 'simple'
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'quorum.local',
 '%_platform_multiplier': 1,
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['mirrored'] = True
config_opts['no-config'] = {'epel-8': {'alternatives': {'alma+epel-8': {'description': ['Builds against '
                                                             'AlmaLinux 8 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-8': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '8 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '8) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL 8 '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'circlelinux+epel-8': {'description': ['Builds '
                                                                    'against '
                                                                    'Circle '
                                                                    'Linux 8 '
                                                                    'repositories, '
                                                                    'together '
                                                                    'with the '
                                                                    'official '
                                                                    'EPEL '
                                                                    'repositories.',
                                                                    'Project '
                                                                    'page: '
                                                                    'https://cclinux.org/']},
                             'rhel+epel-8': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '8 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-8': {'description': ['Builds against '
                                                              'Rocky Linux 8 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}},
 'epel-9': {'alternatives': {'alma+epel-9': {'description': ['Builds against '
                                                             'AlmaLinux 9 '
                                                             'repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'Project page: '
                                                             'https://almalinux.org/']},
                             'centos-stream+epel-9': {'description': ['Builds '
                                                                      'against '
                                                                      'CentOS '
                                                                      'Stream '
                                                                      '9 '
                                                                      'repositories '
                                                                      '(some '
                                                                      'packages '
                                                                      'may be '
                                                                      'a bit '
                                                                      'ahead '
                                                                      'the Red '
                                                                      'Hat '
                                                                      'Enterprise '
                                                                      'Linux '
                                                                      '9) '
                                                                      'together '
                                                                      'with '
                                                                      'the '
                                                                      'official '
                                                                      'EPEL '
                                                                      'repositories.',
                                                                      'Project '
                                                                      'page: '
                                                                      'https://www.centos.org/centos-stream/']},
                             'rhel+epel-9': {'description': ['Builds against '
                                                             'Red Hat '
                                                             'Enterprise Linux '
                                                             '9 repositories, '
                                                             'together with '
                                                             'the official '
                                                             'EPEL '
                                                             'repositories.',
                                                             'This mimics what '
                                                             'is done in the '
                                                             'official EPEL '
                                                             'build system, '
                                                             'but you need a '
                                                             'Red Hat '
                                                             'subscription:',
                                                             'https://rpm-software-management.github.io/mock/Feature-rhelchroots']},
                             'rocky+epel-9': {'description': ['Builds against '
                                                              'Rocky Linux 9 '
                                                              'repositories, '
                                                              'together with '
                                                              'the official '
                                                              'EPEL '
                                                              'repositories.',
                                                              'Project page: '
                                                              'https://rockylinux.org/']}}}}
config_opts['nosync'] = True
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                     'cache_topdir': '/var/container/mock',
                     'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                     'root': 'fedora-rawhide-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                 'cache_topdir': '/var/container/mock',
                 'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                 'compress': None,
                 'dir': '/var/container/mock/fedora-rawhide-x86_64/ccache/u1000/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                 'root': 'fedora-rawhide-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                      'cache_topdir': '/var/container/mock',
                      'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                      'root': 'fedora-rawhide-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                        'cache_topdir': '/var/container/mock',
                        'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                        'root': 'fedora-rawhide-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                  'cache_topdir': '/var/container/mock',
                  'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                  'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                  'root': 'fedora-rawhide-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                   'cache_topdir': '/var/container/mock',
                   'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                   'root': 'fedora-rawhide-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                'cache_topdir': '/var/container/mock',
                'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                'dirs': [],
                'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                'root': 'fedora-rawhide-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                    'cache_topdir': '/var/container/mock',
                    'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                    'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                    'root': 'fedora-rawhide-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                        'cache_topdir': '/var/container/mock',
                        'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                        'root': 'fedora-rawhide-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                     'cache_topdir': '/var/container/mock',
                     'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                     'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                     'root': 'fedora-rawhide-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                  'cache_topdir': '/var/container/mock',
                  'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                  'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                  'root': 'fedora-rawhide-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                     'cache_topdir': '/var/container/mock',
                     'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/container/mock/fedora-rawhide-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                     'root': 'fedora-rawhide-x86_64'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                            'cache_topdir': '/var/container/mock',
                            'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                            'root': 'fedora-rawhide-x86_64'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                  'cache_topdir': '/var/container/mock',
                  'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                  'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                  'root': 'fedora-rawhide-x86_64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                 'cache_topdir': '/var/container/mock',
                 'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                 'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                 'root': 'fedora-rawhide-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
               'cache_topdir': '/var/container/mock',
               'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
               'root': 'fedora-rawhide-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                'cache_topdir': '/var/container/mock',
                'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                'root': 'fedora-rawhide-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/container/mock/fedora-rawhide-x86_64',
                    'cache_topdir': '/var/container/mock',
                    'cachedir': '/var/container/mock/fedora-rawhide-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/container/mock//fedora-rawhide-x86_64/result',
                    'root': 'fedora-rawhide-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '40'
config_opts['root'] = 'fedora-rawhide-{{ target_arch }}'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
Finish: run
```
</details>

**Comment by QuLogic** [comment]
Using `init` first works:
```
$ mock -r fedora-rawhide-x86_64 --clean
$ mock -r fedora-rawhide-x86_64 --init
$ mock -r fedora-rawhide-x86_64 --install python3-tables
```
but the automated-`init` when doing `install` directly doesn't.

**Comment by figless** [comment]
We see the same thing when running builds in koji with mock 5.0 on the build nodes
For the meantime, we've downgraded to mock 4.1

**Comment by praiskup** [comment]
Thank you for the report and comments;  #1209 should fix this.  The thing is that I moved the "resultdir" preparation to an earlier phase of the mock preparation process...  at that point, basedir is not yet prepared with appropriate permissions (if the default basedir is used, the permissions ar OK per mock.rpm file permissions).
