### ISSUE TITLE
How to diable repacking jar ?

### ISSUE THREAD

**Issue by Erazx** [rpm-software-management/mock#133]
I've tried adding `%define __os_install_post %{nil}` Or `%define __jar_repack %{nil}`。
Still got some result: 
```
Mock Version: 1.4.6
ENTER ['do'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target noarch --nodeps /builddir/build/SPECS/reports.spec'], nspawn_args=[]shell=Falseuid=1000env={'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '}chrootPath='/tmp/mock/lib/epel-6-x86_64/root'gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x2521750>printOutput=True)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target noarch --nodeps /builddir/build/SPECS/reports.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '} and shell False
Building target platforms: noarch
Building for target noarch
Wrote: /builddir/build/SRPMS/reports-1.1.1-1.el6.src.rpm
Child return code was: 0
ENTER ['do'](['bash', '--login', '-c', u'/usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/reports.spec'], nspawn_args=[]shell=Falseuid=1000env={'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '}chrootPath='/tmp/mock/lib/epel-6-x86_64/root'gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x2521750>printOutput=True)
Executing command: ['bash', '--login', '-c', u'/usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/reports.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '} and shell False
Building target platforms: noarch
Building for target noarch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.ykLCwj
+ umask 022
+ cd /builddir/build/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /builddir/build/BUILD
+ rm -rf reports-1.1.1
+ /usr/bin/unzip -qq /builddir/build/SOURCES/report-1.1.1.jar
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd reports-1.1.1
RPM build errors:
/var/tmp/rpm-tmp.ykLCwj: line 38: cd: reports-1.1.1: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.ykLCwj (%prep)
    Bad exit status from /var/tmp/rpm-tmp.ykLCwj (%prep)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 598, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/reports.spec
```

**Comment by xsuchy** [comment]
Without the spec pasted here, there is nothing I can do.
And this is packaging question, so it should go rather to stackoverflow or https://fedoraproject.org/wiki/SIGs/Java#Mailing_list
Anyway I guess that you are using %setup macro, which you should not use if you do not want to repack jar.
