### ISSUE TITLE
Can not use NFS for resultdir with hw_info plugin

### ISSUE THREAD

**Issue by treydock** [rpm-software-management/mock#144]
This is a continuation of #85 which is closed.

I'm unable to use NFS as resultdir when hw_info plugin is enabled using mock 1.4.7.  The file that gets Permissions denied for mock can be created and modified outside mock without issue.  All commands were run as same account that is not root.

```
$ mock --resultdir /users/sysp/tdockendorf/tmp --init
INFO: mock.py version 1.4.7 starting (python version = 2.7.5)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: root cache aged out! cache will be rebuilt
INFO: enabled yum cache
Start: cleaning yum metadata
Finish: cleaning yum metadata
INFO: enabled HW Info plugin
ERROR: [Errno 13] Permission denied: '/users/sysp/tdockendorf/tmp/hw_info.log'
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 949, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 749, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 776, in run_command
    commands.init()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/backend.py", line 164, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/buildroot.py", line 92, in initialize
    self._init(prebuild=prebuild, do_log=do_log)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/buildroot.py", line 127, in _init
    self.plugins.call_hooks('preinit')
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/plugin.py", line 78, in call_hooks
    hook(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/plugins/hw_info.py", line 38, in _PreInitHook
    out = codecs.open(out_file, 'w', 'utf-8', 'replace')
  File "/usr/lib64/python2.7/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: '/users/sysp/tdockendorf/tmp/hw_info.log'
```

```
$ touch /users/sysp/tdockendorf/tmp/hw_info.log
$ echo foo > /users/sysp/tdockendorf/tmp/hw_info.log
$ cat /users/sysp/tdockendorf/tmp/hw_info.log
foo
```

**Comment by Frodox** [comment]
same as #85 :D

**Comment by xsuchy** [comment]
Closing in favour of #85
