### ISSUE TITLE
mockchain still creates a root-owned resultdir 

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#1490]
Two subsequent runs of mockchain cause this traceback:
```
$ mockchain -r epel-10-x86_64 /tmp/python-responses/python-responses-0.18.0-1.el9.src.rpm /tmp/python-freezegun/python-freezegun-1.2.2-9.fc42.src.rpm /tmp/python-humanize/python-humanize-4.9.0-2.fc42.src.rpm /home/praiskup/rh/packages/copr-cli/copr-cli-2.0-1.el10_0.src.rpm

## mockchain is deprecated, use mock --chain instead ##

INFO: mock.py version 5.9 starting (python version = 3.13.0, NVR = mock-5.9-1.git.3831.cdc2b58.fc41), args: /usr/libexec/mock/mock --chain -r epel-10-x86_64 /tmp/python-responses/python-responses-0.18.0-1.el9.src.rpm /tmp/python-freezegun/python-freezegun-1.2.2-9.fc42.src.rpm /tmp/python-humanize/python-humanize-4.9.0-2.fc42.src.rpm /home/praiskup/rh/packages/copr-cli/copr-cli-2.0-1.el10_0.src.rpm
Start(bootstrap): init plugins
INFO: tmpfs initialized
INFO: selinux enabled
INFO: chroot_scan: initialized
Finish(bootstrap): init plugins
Start: init plugins
INFO: tmpfs initialized
INFO: selinux enabled
INFO: chroot_scan: initialized
Finish: init plugins
INFO: Signal handler active
Start: run
INFO: chroot_scan: 3 files copied to /var/lib/mock/centos-stream+epel-10-x86_64/result/chroot_scan
INFO: /var/lib/mock/centos-stream+epel-10-x86_64/root/var/log/dnf.log
/var/lib/mock/centos-stream+epel-10-x86_64/root/var/log/dnf.librepo.log
/var/lib/mock/centos-stream+epel-10-x86_64/root/var/log/dnf.rpm.log
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1135, in <module>
    exitStatus = main()
  File "/usr/lib/python3.13/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 887, in main
    result = run_command(options, args, config_opts, commands, buildroot)
  File "/usr/lib/python3.13/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 930, in run_command
    commands.init(do_log=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.13/site-packages/mockbuild/backend.py", line 156, in init
    self.buildroot.resetLogging()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.13/site-packages/mockbuild/buildroot.py", line 654, in resetLogging
    fh = logging.FileHandler(fullPath, "a+")
  File "/usr/lib64/python3.13/logging/__init__.py", line 1218, in __init__
    StreamHandler.__init__(self, self._open())
                                 ~~~~~~~~~~^^
  File "/usr/lib64/python3.13/logging/__init__.py", line 1247, in _open
    return open_func(self.baseFilename, self.mode,
                     encoding=self.encoding, errors=self.errors)
PermissionError: [Errno 13] Permission denied: '/var/lib/mock/centos-stream+epel-10-x86_64/result/state.log'
```

Caused by root ownership:

```
$ ls -alh /var/lib/mock/centos-stream+epel-10-x86_64/result/
total 12K
drwxrwxr-x. 3 root     root 4.0K říj 23 12:29 .
drwxrwxr-x. 4 root     mock 4.0K říj 23 12:29 ..
drwxrwxr-x. 3 praiskup mock 4.0K říj 23 12:29 chroot_scan
```

**Comment by praiskup** [comment]
The problem was that the plugin's resultdir was crated globally in /var/lib/mock/<chroot>/result, not in the per-package resultdir like /var/tmp/mock-chain-root-23693-8id_zl19/results/.
