### ISSUE TITLE
Regular build failures with systemd-nspawn in 1.4.8

### ISSUE THREAD

**Issue by pghmcfc** [rpm-software-management/mock#150]
Since updating to 1.4.8, I've been getting lots of build failures (intermittent but frequent) like this:
```
Mock Version: 1.4.8
ENTER ['do'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/moin-theme-widget.spec'], chrootPath='/var/lib/mock/city-fan-fedora-23-x86_64/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'en_GB.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7fa234903e10>timeout=0uid=1000gid=101user='mockbuild'nspawn_args=[]unshare_net=FalseprintOutput=True)
Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '5e2155c65c0e41bf8926dd9a84f074a2', '-D', '/var/lib/mock/city-fan-fedora-23-x86_64/root', '-a', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=en_GB.UTF-8', '-u', 'mockbuild', 'bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/moin-theme-widget.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'en_GB.UTF-8'} and shell False
Failed to register machine: File exists
Parent died too early
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/util.py", line 619, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed:
 # /usr/bin/systemd-nspawn -q -M 5e2155c65c0e41bf8926dd9a84f074a2 -D /var/lib/mock/city-fan-fedora-23-x86_64/root -a --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_GB.UTF-8 -u mockbuild bash --login -c /usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/moin-theme-widget.spec
```
This is punctuated by lots of warnings like this on the console:
```
WARNING: Machine 0285501b5643408f8bff387a151744fc still running. Killing...
```
It seems that the attempts to kill the machines are not going too well.

I currently have 2183 machines listed by `systemctl list-machines` on my builder. I could probably do with killing most of them.

**Comment by pghmcfc** [comment]
A bit more on this. I rebooted my builder soon after reporting the issue here, and all was well again until today, when the machines started to become zombies again. They're all in state "closing" and I don't seem to be able to get rid of them (`machinectl terminate ...` has no effect) even though none appear to have any processes running. Maybe it's actually a systemd issue?

**Comment by xsuchy** [comment]
@msekletar  any idea?

**Comment by pghmcfc** [comment]
Maybe related to https://github.com/systemd/systemd/issues/7236

**Comment by pghmcfc** [comment]
I did manage to work around this by doing `systemctl restart systemd-machined`, which got rid of the stale mock builders but thankfully left my KVM/qemu virtual machines intact.

**Comment by praiskup** [comment]
Is this still an issue (with latest systemd and mock v1.4.20)?

**Comment by pghmcfc** [comment]
@praiskup, no I've not seen this for quite a long time now.

**Comment by praiskup** [comment]
Thank you for the feedback, closing then.
