### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 207-210: ordinal not in range(128)

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/mock#176]
Taken from https://bodhi.fedoraproject.org/updates/FEDORA-2018-c17daa06f6

```
$ tito build --offline --builder mock --arg mock=fedora-27-x86_64 --rpm --test
Creating output directory: /tmp/tito
Building package [pgadmin3-1.24.0-2]
Creating rpms for pgadmin3-git-8.cb9dc55 in mock: fedora-27-x86_64

Wrote: /tmp/tito/pgadmin3-1.24.1-2.git.8.cb9dc55.fc27.src.rpm

Using srpm: /tmp/tito/pgadmin3-1.24.1-2.git.8.cb9dc55.fc27.src.rpm
Initializing mock...
INFO: mock.py version 1.4.9 starting (python version = 3.6.4)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: root cache aged out! cache will be rebuilt
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Mock Version: 1.4.9
INFO: Mock Version: 1.4.9
Start: dnf install
Finish: dnf install
Start: creating root cache
ERROR: 'ascii' codec can't encode characters in position 207-210: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 959, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 759, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 786, in run_command
    commands.init()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/backend.py", line 164, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/buildroot.py", line 92, in initialize
    self._init(prebuild=prebuild, do_log=do_log)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/buildroot.py", line 182, in _init
    self.plugins.call_hooks('postinit')
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugin.py", line 78, in call_hooks
    hook(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugins/root_cache.py", line 163, in _rootCachePostInitHook
    self._rebuild_root_cache()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugins/root_cache.py", line 200, in _rebuild_root_cache
    l.write(self.buildroot.pkg_manager.init_install_output)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 207-210: ordinal not in range(128)


ERROR: Error running command: mock  -r fedora-27-x86_64 --init

Status code: 1
....
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/tito/cli.py", line 203, in main
    return module.main(argv)
  File "/usr/lib/python3.6/site-packages/tito/cli.py", line 378, in main
    return builder.run(self.options)
  File "/usr/lib/python3.6/site-packages/tito/builder/main.py", line 156, in run
    self.rpm()
  File "/usr/lib/python3.6/site-packages/tito/builder/main.py", line 1139, in rpm
    self._build_in_mock()
  File "/usr/lib/python3.6/site-packages/tito/builder/main.py", line 1149, in _build_in_mock
    run_command_func("mock %s -r %s --init" % (self.mock_cmd_args, self.mock_tag))
  File "/usr/lib/python3.6/site-packages/tito/common.py", line 468, in run_command_print
    raise RunCommandException(command, status, "\n".join(output))
tito.exception.RunCommandException: Error running command: mock  -r fedora-27-x86_64 --init
```
downgrade to `mock.noarch 1.4.6-1.fc27` solves this problem   
https://bugzilla.redhat.com/show_bug.cgi?id=1564035

**Comment by didib** [comment]
This now happened to us [1] on fcraw:

...
11:06:14    File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
11:06:14      result = func(*args, **kw)
11:06:14    File "/usr/lib/python2.7/site-packages/mockbuild/plugins/root_cache.py", line 219, in _rebuild_root_cache
11:06:14      cache_log.write(self.buildroot.pkg_manager.init_install_output.encode())
11:06:14  UnicodeEncodeError: 'ascii' codec can't encode characters in position 73796-73798: ordinal not in range(128)

@xsuchy , Known issue? Thanks!

[1] https://jenkins.ovirt.org/job/ovirt-setup-lib_standard-check-patch/9/consoleFull
