### ISSUE TITLE
mock fails with NFS-mounted /home (unable to create files in resultdir)

### ISSUE THREAD

**Issue by amessina** [rpm-software-management/mock#341]
### Short description of the problem
After upgrading to mock-1.4.19-1, mock fails when user has `/home` mounted via NFS.  It appears that files within `./results_<packagename>/` cannot be created.  This issue did not occur with the previous version of mock in Fedora 30.

### Output of `rpm -q mock`
mock-1.4.19-1.fc30.noarch

### Steps to reproduce issue
1. Work from NFS-mounted `/home`
2. Run fedpkg (or in this case, msspkg, a local clone of fedpkg) mockbuild
3. See the following...

```
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 967, in <module>
    exitStatus = main()
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 744, in main
    result = run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 848, in run_command
    mockbuild.rebuild.do_rebuild(config_opts, commands, buildroot, options, args)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/rebuild.py", line 82, in do_rebuild
    post=post_build, clean=clean)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/rebuild.py", line 24, in rebuild_generic
    commands.init(prebuild=not config_opts.get('short_circuit'))
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/backend.py", line 173, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/buildroot.py", line 94, in initialize
    self._init(prebuild=prebuild, do_log=do_log)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/buildroot.py", line 135, in _init
    self._resetLogging()
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 95, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/buildroot.py", line 354, in _resetLogging
    fh = logging.FileHandler(fullPath, "a+")
  File "/usr/lib64/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/amessina/public_git/rpms/msspkg-minimal/results_msspkg-minimal/0.3/1.fc30/state.log'
WARNING: unable to delete selinux filesystems (/tmp/mock-selinux-plugin.b8zylvxp): [Errno 1] Operation not permitted: '/tmp/mock-selinux-plugin.b8zylvxp'
```

**Comment by xsuchy** [comment]
Can you try, if `--old-chroot` workaround your issue?

**Comment by amessina** [comment]
Unfortunately `--old-chroot` did not make a difference.  Config debug output:
[mock_debug_config.log](https://github.com/rpm-software-management/mock/files/3648431/mock_debug_config.log)

**Comment by praiskup** [comment]
This is not new in mock, `mock-1.4.14-1.fc30.noarch` behaves the same:
`PermissionError: [Errno 13] Permission denied: '/homedirs/praiskup/cpio/results_cpio/2.12/12.fc32/hw_info.log'`

**Comment by xsuchy** [comment]
Maybe related https://github.com/rpm-software-management/mock/issues/85

**Comment by praiskup** [comment]
Doesn't seem to be, I disabled the hw_info and still the same issue. 

Doesn't seem to be triggered by mock, it looks like someone else (probably rpkg/fedpkg) decided to write logs to `$HOME/cpio/results_cpio/2.12/12.fc32/`.

**Comment by praiskup** [comment]
Ok, this is probably related to #322.  If the mountpoint is configured with `root_squash` option, mock isn't able to create root owned files on the mount point.  The rpkg/pyrpkg seems to use $HOME for mock resultdir at least since Y2015 (I haven't looked too far to history).
