### ISSUE TITLE
mageia-6-* configs broken (only with bootstrap ON)

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#523]
```

ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M fb76da57efef409eb049cf5b5c32dd55 -D /var/lib/mock/mageia-6-i586-bootstrap/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.zygt8w1t:/etc/resolv.conf --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/mageia-6-i586/rpmconfig --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 /usr/bin/dnf --installroot /var/lib/mock/mageia-6-i586/root/ --releasever 6 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk install basesystem-minimal rpm-build rpm-mageia-setup rpm-mageia-setup-build --setopt=tsflags=nocontexts
DEBUG: Unsharing. Flags: 134217728
determining the fastest mirror (4 hosts).. done.
determining the fastest mirror (2 hosts).. done.
Last metadata expiration check: 0:00:00 ago on Tue Mar 10 11:35:05 2020.
Failed to set locale, defaulting to C
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.5/site-packages/dnf/cli/main.py", line 146, in resolving
    base.resolve(cli.demands.allow_erasing)
  File "/usr/lib/python3.5/site-packages/dnf/base.py", line 687, in resolve
    name=self.conf.protected_packages))
  File "/usr/lib/python3.5/site-packages/dnf/query.py", line 84, in filter
    return super(Query, self).filter(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/hawkey/__init__.py", line 392, in filter
    return new_query.filterm(*lst, **kwargs)
  File "/usr/lib/python3.5/site-packages/hawkey/__init__.py", line 398, in filterm
    super(Query, self).filter(*arg_tuple)
TypeError: Expected a sequence.
```

**Comment by Conan-Kudo** [comment]
I can't fix it anymore, Mageia 6 is EOL.

**Comment by praiskup** [comment]
Ack, can we EOL it in mock-core-configs then?

**Comment by Conan-Kudo** [comment]
Yup, go for it!
