### ISSUE TITLE
opensuse-leap-15.0 configs don't work

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#530]
```

 # /usr/bin/systemd-nspawn -q -M 2d80100ad39e443ea9278b954dfcbd4f -D /var/lib/mock/opensuse-leap-15.0-x86_64-bootstrap-39605-3059/root -a --capability=cap_ipc_lock --bind=/tmp/mock-resolv.aso_pfc2:/etc/resolv.conf --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/var/lib/mock/opensuse-leap-15.0-x86_64-39605-3059/rpmconfig --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.UTF-8 --setenv=LC_MESSAGES=C.UTF-8 /usr/bin/dnf --installroot /var/lib/mock/opensuse-leap-15.0-x86_64-39605-3059/root/ --releasever 15.0 --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=spacewalk install patterns-devel-base-devel_rpm_build --setopt=tsflags=nocontexts
DEBUG: Unsharing. Flags: 134217728
openSUSE Leap 15.0 - x86_64 - OSS                41 MB/s |  34 MB     00:00
openSUSE Leap 15.0 - x86_64 - Updates - OSS      37 MB/s |  77 MB     00:02
Last metadata expiration check: 0:00:10 ago on Wed Mar 11 07:51:55 2020.
Failed to set locale, defaulting to C
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 146, in resolving
    base.resolve(cli.demands.allow_erasing)
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 687, in resolve
    name=self.conf.protected_packages))
  File "/usr/lib/python3.6/site-packages/dnf/query.py", line 84, in filter
    return super(Query, self).filter(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/hawkey/__init__.py", line 392, in filter
    return new_query.filterm(*lst, **kwargs)
  File "/usr/lib64/python3.6/site-packages/hawkey/__init__.py", line 398, in filterm
    super(Query, self).filter(*arg_tuple)
TypeError: Expected a sequence.


real    1m22.446s
user    1m16.438s
sys     0m4.425s
FAILED: opensuse-leap-15.0-x86_64.cfg
```

**Comment by Conan-Kudo** [comment]
I can't fix openSUSE Leap 15.0 anymore, it's EOL.
