### ISSUE TITLE
setup subscription-manager.conf fails on non-registered machine

### ISSUE THREAD

**Issue by Frodox** [rpm-software-management/mock#55]
I'm trying to setup subscription-manager.conf on centos machine, like (not matter which config)
```
config_opts['subscription-manager.conf'] = """
[main]
enabled=0
"""
```
and get an error:
```
ERROR: [Errno 2] No such file or directory: '/etc/rhsm/rhsm.conf'
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 885, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 701, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 726, in run_command
    commands.init()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/backend.py", line 124, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/buildroot.py", line 90, in initialize
    self._init(prebuild=prebuild, do_log=do_log)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/buildroot.py", line 139, in _init
    self.pkg_manager.initialize()
  File "/usr/lib/python2.7/site-packages/mockbuild/package_manager.py", line 146, in initialize
    self.initialize_config()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/package_manager.py", line 232, in initialize_config
    self.buildroot.make_chroot_path('etc', 'rhsm'))
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/etc/rhsm/rhsm.conf'
```

Looks like [mock copies `/etc/rhsm/rhsm.conf` from host](https://github.com/rpm-software-management/mock/blob/devel/py/mockbuild/package_manager.py#L242) (which doesn't exist).

Should there be a note/wiki about 'how to use this plugin correctly'..? Looks like nobody use it :)

**Comment by xsuchy** [comment]
I actually never used it, but... you should first register your host machine and mock copy rhsm.conf and pki files for subscription-manager so the chroot should be able to download packages from RH CDN.
