### ISSUE TITLE
KeyError: 'getpwuid(): uid not found'

### ISSUE THREAD

**Issue by sharkcz** [rpm-software-management/mock#571]
### Short description of the problem

Mock fails with a traceback when trying to rebuild a srpm on F-31 s390x system. It happens after the build deps have been installed.

````
...
Finish: build setup for atasm-1.08-4.fc33.src.rpm
Start: Outputting list of installed packages
Finish: Outputting list of installed packages
Finish: build phase for atasm-1.08-4.fc33.src.rpm
ERROR: Exception(atasm-1.08-4.fc33.src.rpm) Config(fedora-31-s390x) 3 minutes 56 seconds
INFO: Results and/or logs in: /var/lib/mock/fedora-31-s390x/result
ERROR: 'getpwuid(): uid not found'
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1026, in <module>
    exitStatus = main()
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 805, in main
    result = run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 907, in run_command
    mockbuild.rebuild.do_rebuild(config_opts, commands, buildroot, options, args)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/rebuild.py", line 84, in do_rebuild
    post=post_build, clean=clean)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/rebuild.py", line 25, in rebuild_generic
    ret = cmd(item)
  File "/usr/lib/python3.7/site-packages/mockbuild/rebuild.py", line 65, in build
    check=config_opts['check'], spec=options.spec)
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/backend.py", line 312, in build
    self.plugins.call_hooks('prebuild')
  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.7/site-packages/mockbuild/plugin.py", line 78, in call_hooks
    hook(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/mockbuild/plugins/package_state.py", line 77, in _installedPreBuildHook
    output, _ = self.buildroot.doOutChroot(cmd, returnOutput=1, shell=True)
  File "/usr/lib/python3.7/site-packages/mockbuild/buildroot.py", line 244, in doOutChroot
    return self.bootstrap_buildroot.doChroot(command, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/mockbuild/buildroot.py", line 259, in doChroot
    kargs['gid'] = pwd.getpwuid(kargs['uid'])[0]
KeyError: 'getpwuid(): uid not found'

````

### Output of `rpm -q mock`

mock-2.2-1.fc31.noarch

### Steps to reproduce issue

1. mock -r fedora-31-s390x foo.src.rpm

Do not forget to mention full commandline with the mock command you executed.

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>
````
INFO: mock.py version 2.2 starting (python version = 3.7.7)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
config_opts['bootstrap_image'] = 'fedora:{{ releasever }}'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'default'
config_opts['chroot_setup_cmd'] = 'install @{% if mirrored %}buildsys-{% endif %}build'
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/default.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/fedora-31-s390x.cfg',
 '/etc/mock/templates/fedora-branched.tpl']
config_opts['dist'] = 'fc{{ releasever }}'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'install_weak_deps=0\n'
 'metadata_expire=0\n'
 'best=1\n'
 'module_platform_id=platform:f{{ releasever }}\n'
 'protected_packages=\n'
 '\n'
 '# repos\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/f{{ releasever '
 '}}-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled={{ not mirrored }}\n'
 'skip_if_unavailable=False\n'
 '\n'
 '{% if mirrored %}\n'
 '[fedora]\n'
 'name=fedora\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates]\n'
 'name=updates\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing]\n'
 'name=updates-testing\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-debuginfo]\n'
 'name=fedora-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-debuginfo]\n'
 'name=updates-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-testing-debuginfo]\n'
 'name=updates-testing-debuginfo\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-source]\n'
 'name=fedora-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-source]\n'
 'name=updates-source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-{{ '
 'releasever }}-primary\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '# modular\n'
 '\n'
 '[fedora-modular]\n'
 'name=Fedora Modular $releasever - $basearch\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-$releasever&arch=$basearch\n'
 '# if you want to enable it, you should set best=0\n'
 '# see https://bugzilla.redhat.com/show_bug.cgi?id=1673851\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Debug\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-debug-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[fedora-modular-source]\n'
 'name=Fedora Modular $releasever - Source\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-source-$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-$releasever-primary\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular]\n'
 'name=Fedora Modular $releasever - $basearch - Updates\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-debuginfo]\n'
 'name=Fedora Modular $releasever - $basearch - Updates - Debug\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/$basearch/debug/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-debug-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[updates-modular-source]\n'
 'name=Fedora Modular $releasever - Updates Source\n'
 '#baseurl=http://download.fedoraproject.org/pub/fedora/linux/updates/$releasever/Modular/SRPMS/\n'
 'metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-source-f$releasever&arch=$basearch\n'
 'enabled=0\n'
 'repo_gpgcheck=0\n'
 'type=rpm\n'
 'gpgcheck=1\n'
 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch\n'
 'skip_if_unavailable=False\n'
 '{% endif %}\n')
config_opts['enable_disable_repos'] = []
config_opts['environment'] = {'HOME': '/builddir',
 'HOSTNAME': 'mock',
 'LANG': 'C.UTF-8',
 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin',
 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"',
 'PS1': '<mock-chroot> \\s-\\v\\$ ',
 'SHELL': '/bin/bash',
 'TERM': 'xterm-256color'}
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('s390x',)
config_opts['macros'] = {'%_buildhost': 'hicsuntdracones',
 '%_netsharedpath': '/proc:/sys',
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['mirrored'] = True
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.j04wj0cp:/etc/resolv.conf',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-31-s390x',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                     'root': 'fedora-31-s390x'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/fedora-31-s390x',
                 'compress': None,
                 'dir': '/var/cache/mock/fedora-31-s390x/ccache/u1001/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                 'root': 'fedora-31-s390x'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/fedora-31-s390x',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                      'root': 'fedora-31-s390x'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-31-s390x',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                        'root': 'fedora-31-s390x'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-31-s390x',
                  'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                  'root': 'fedora-31-s390x'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/fedora-31-s390x',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                   'root': 'fedora-31-s390x'},
 'mount_enable': False,
 'mount_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-31-s390x',
                'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                'root': 'fedora-31-s390x'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-31-s390x',
                    'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                    'root': 'fedora-31-s390x'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/fedora-31-s390x',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/fedora-31-s390x',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                        'root': 'fedora-31-s390x'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-31-s390x',
                     'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                     'root': 'fedora-31-s390x'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-31-s390x',
                  'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                  'root': 'fedora-31-s390x'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/fedora-31-s390x',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/fedora-31-s390x',
                     'compress_program': 'pigz',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/fedora-31-s390x/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.gz',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                     'root': 'fedora-31-s390x',
                     'tar': 'gnutar'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/fedora-31-s390x',
                  'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                  'root': 'fedora-31-s390x'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/fedora-31-s390x',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/fedora-31-s390x/result',
               'root': 'fedora-31-s390x'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/fedora-31-s390x',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                'root': 'fedora-31-s390x'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/fedora-31-s390x',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/fedora-31-s390x',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/fedora-31-s390x/result',
                    'root': 'fedora-31-s390x'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '31'
config_opts['root'] = 'fedora-{{ releasever }}-{{ target_arch }}'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 's390x'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 's390x'
config_opts['use_container_host_hostname'] = False
config_opts['verbose'] = 1
Finish: run
````
</details>

I haven't been able to reproduce the failure on a non-s390x system. If you want access to the s390x system with the reproducer, let me know.

**Comment by sharkcz** [comment]
And I have reproduced the failure on a Rawhide/s390x system too ...

**Comment by sharkcz** [comment]
Seems to be version 2.2 related, when I downgraded to 2.1 (plus mock-core-configs-32.5-1.fc31), the srpm builds OK.

**Comment by praiskup** [comment]
Thanks for the report, there's [a bug](https://github.com/rpm-software-management/mock/blob/8c981ae0fc7a1684a64b7f526745bc959e33ae85/mock/py/mockbuild/buildroot.py#L262-L263) in old code triggered by a93aa9f68fa16f6bbeff1923a28af280e283528d.

**Comment by praiskup** [comment]
Work-around is to either specify the etc/passwd entry, or to disable package state plugin.

**Comment by nirik** [comment]
Is there an ETA for a release with a fix here? we are hoping to update mock/koji/builder stack in fedora and need this solved before that. :)

**Comment by praiskup** [comment]
Meh, I wanted to wrap release this week, but now it is clear that I have to postpone
it for the next week.
