### ISSUE TITLE
ERROR: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by cottsay** [rpm-software-management/mock#605]
### Short description of the problem
A regression appears to have broken support for macro definitions that don't have the leading `%` on keys. Builds that were working a week ago are now breaking, unless the configurations are updated so that every macro includes the leading `%` on the key.

### Output of `rpm -q mock`

mock-2.4-1.fc32.noarch

### Steps to reproduce issue

1. Add a macro definition to a mock config without a `%` (e.x. `config_opts['macros']['debug_package'] = '%{nil}'`)
2. Invoke almost any mock operation, such as `mock --debug-config`

### Any additional notes

<details>
  <summary>
    <p>Output of `mock --debug-config`</p>
  </summary>

```
ERROR: dictionary keys changed during iteration
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1026, in <module>
    exitStatus = main()
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 652, in main
    config_opts = util.load_config(config_path, options.chroot, uidManager, __VERSION__, PKGPYTHONDIR)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 1645, in load_config
    do_update_config(log, config_opts, chroot_cfg_path, uidManager, name, skipError=False)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 1566, in do_update_config
    check_macro_definition(config_opts)
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 1673, in check_macro_definition
    for k, v in config_opts['macros'].items():
RuntimeError: dictionary keys changed during iteration
```
</details>

**Comment by cottsay** [comment]
I'm really not sure what changed here. Even after downgrading mock, rpm, and python3 on Fedora 32, I'm still seeing the problem.

No signs of the regression in Fedora 31 at all.

**Comment by praiskup** [comment]
I bet this is a result of Mock bug (changing dict while iterating over it) some recent Python change.
We've seen recently a similar thing in [copr and packit](https://github.com/packit-service/packit-service/pull/626).
