### ISSUE TITLE
external:pypi:.. installs for Python 3.9 for EPEL 8 chroot

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/mock#761]
### Short description of the problem

I've decided to try out the [external deps feature](https://github.com/rpm-software-management/mock/wiki/Feature-external-deps).

I have this in the spec file:

```
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools
BuildRequires:  python3-pygments
BuildRequires:  python3-requests
BuildRequires:  python3-requests-toolbelt
BuildRequires:  python3-pytest
BuildRequires:  external:pypi:pytest-httpbin
```

In an EPEL 8 chroot, it installs all RPM packages for Python 3.6, but pytest-httpbin for Python 3.9. Hence, it does not really help at all.

### Output of `rpm -q mock`

mock-2.12-1.fc33.noarch

### Steps to reproduce issue

1. Get this spec file: [httpie.spec](https://github.com/rpm-software-management/mock/files/6982179/httpie.spec.txt)
2. Fetch all the sources and patches (to be found in httpie's dist git, branch rawhide)
3. Run: `fedpkg --release epel8 mockbuild -N -- --config-opts external_buildrequires=True`

It runs (from root.log):

```
Executing command: ['pip3', 'install', '--root', '/var/lib/mock/epel-8-x86_64/root', 'pytest-httpbin'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'C.UTF-8'} and shell False
Collecting pytest-httpbin
Downloading pytest_httpbin-1.0.0-py2.py3-none-any.whl (9.8 kB)
Collecting httpbin
Downloading httpbin-0.7.0-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from pytest-httpbin) (1.15.0)
Collecting werkzeug>=0.14.1
Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Requirement already satisfied: MarkupSafe in /usr/lib64/python3.9/site-packages (from httpbin->pytest-httpbin) (1.1.1)
Collecting brotlipy
Downloading brotlipy-0.7.0-cp39-cp39-manylinux1_x86_64.whl (1.1 MB)
Collecting itsdangerous
Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Requirement already satisfied: decorator in /usr/lib/python3.9/site-packages (from httpbin->pytest-httpbin) (4.4.2)
Collecting Flask
Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
Collecting raven[flask]
Downloading raven-6.10.0-py2.py3-none-any.whl (284 kB)
Requirement already satisfied: cffi>=1.0.0 in /usr/lib64/python3.9/site-packages (from brotlipy->httpbin->pytest-httpbin) (1.14.1)
Requirement already satisfied: click>=7.1.2 in /usr/lib/python3.9/site-packages (from Flask->httpbin->pytest-httpbin) (7.1.2)
Collecting Jinja2>=3.0
Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting blinker>=1.1; extra == "flask"
Downloading blinker-1.4.tar.gz (111 kB)
Requirement already satisfied: pycparser in /usr/lib/python3.9/site-packages (from cffi>=1.0.0->brotlipy->httpbin->pytest-httpbin) (2.20)
Requirement already satisfied: ply==3.11 in /usr/lib/python3.9/site-packages (from pycparser->cffi>=1.0.0->brotlipy->httpbin->pytest-httpbin) (3.11)
Building wheels for collected packages: blinker
Building wheel for blinker (setup.py): started
Building wheel for blinker (setup.py): finished with status 'done'
Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13452 sha256=8aaa7e900602ea926cc67d217f654bca66c1698a82031cfce0dcac850d3494a0
Stored in directory: /builddir/.cache/pip/wheels/50/93/f8/4f0a42a03a06626d675f13907b6982ad5ecff383530af5a900
Successfully built blinker
Installing collected packages: werkzeug, brotlipy, itsdangerous, Jinja2, Flask, blinker, raven, httpbin, pytest-httpbin
WARNING: The script flask is installed in '/var/lib/mock/epel-8-x86_64/root/usr/local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script raven is installed in '/var/lib/mock/epel-8-x86_64/root/usr/local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
jinja2 3.0.1 requires MarkupSafe>=2.0, but you'll have markupsafe 1.1.1 which is incompatible.
Successfully installed Flask-2.0.1 Jinja2-3.0.1 blinker-1.4 brotlipy-0.7.0 httpbin-0.7.0 itsdangerous-2.0.1 pytest-httpbin-1.0.0 raven-6.10.0 werkzeug-2.0.1
Child return code was: 0
```

But at the end it fails with (from build.log):

```
+ /usr/bin/pytest-3 -v
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 329, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/builddir/build/BUILD/httpie-2.4.0/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 360, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/builddir/build/BUILD/httpie-2.4.0/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/builddir/build/BUILD/httpie-2.4.0/tests/conftest.py", line 3, in <module>
    from pytest_httpbin import certs
ModuleNotFoundError: No module named 'pytest_httpbin'
ERROR: could not load /builddir/build/BUILD/httpie-2.4.0/tests/conftest.py
```

I've examined the chroot and the extra pip-installed packages are in:

```
<mock-chroot> sh-4.4# ls /usr/local/lib/python3.9/site-packages/ -1
Flask-2.0.1.dist-info
Jinja2-3.0.1.dist-info
Werkzeug-2.0.1.dist-info
blinker
blinker-1.4.dist-info
flask
httpbin
httpbin-0.7.0.dist-info
itsdangerous
itsdangerous-2.0.1.dist-info
jinja2
pytest_httpbin
pytest_httpbin-1.0.0.dist-info
raven
raven-6.10.0.dist-info
werkzeug
```

Which is not what I would expect on EPEL 8.

Assumption: Seems like my own pip is used here instead of the one from bootstrap chroot.

### Any additional notes

<details>
  <summary>

Output of `mock --debug-config`

  </summary>

```
config_opts['bootstrap_image'] = 'quay.io/centos/centos:8'
config_opts['build_log_fmt_str'] = '%(message)s'
config_opts['cache_alterations'] = False
config_opts['chroot_name'] = 'epel-8-x86_64'
config_opts['chroot_setup_cmd'] = ('install tar gcc-c++ redhat-rpm-config redhat-release which xz sed make bzip2 '
 'gzip gcc coreutils unzip shadow-utils diffutils cpio bash gawk rpm-build '
 'info patch util-linux findutils grep epel-release epel-rpm-macros '
 'fedpkg-minimal')
config_opts['cleanup_on_failure'] = False
config_opts['cleanup_on_success'] = False
config_opts['config_file'] = '/etc/mock/epel-8-x86_64.cfg'
config_opts['config_path'] = '/etc/mock'
config_opts['config_paths'] = ['/etc/mock/site-defaults.cfg',
 '/etc/mock/epel-8-x86_64.cfg',
 '/etc/mock/templates/centos-8.tpl',
 '/etc/mock/templates/epel-8.tpl',
 '/home/churchyard/.config/mock.cfg']
config_opts['dist'] = 'el8'
config_opts['dnf.conf'] = ('\n'
 '[main]\n'
 'keepcache=1\n'
 'debuglevel=2\n'
 'reposdir=/dev/null\n'
 'logfile=/var/log/yum.log\n'
 'retries=20\n'
 'obsoletes=1\n'
 'gpgcheck=0\n'
 'assumeyes=1\n'
 'syslog_ident=mock\n'
 'syslog_device=\n'
 'metadata_expire=0\n'
 'mdpolicy=group:primary\n'
 'best=1\n'
 'protected_packages=\n'
 'module_platform_id=platform:el8\n'
 'user_agent={{ user_agent }}\n'
 '\n'
 '[baseos]\n'
 'name=CentOS-$releasever - Base\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=BaseOS&infra=$infra\n'
 'failovermethod=priority\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[appstream]\n'
 'name=CentOS-$releasever - AppStream\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=AppStream&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/AppStream/$basearch/os/\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[powertools]\n'
 'name=CentOS-$releasever - PowerTools\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=PowerTools&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/PowerTools/$basearch/os/\n'
 'gpgcheck=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[devel]\n'
 'name=CentOS-$releasever - Devel WARNING! FOR BUILDROOT USE ONLY!\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=Devel&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/$contentdir/$releasever/Devel/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[plus]\n'
 'name=CentOS-$releasever - Plus\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=centosplus&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/centosplus/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[cr]\n'
 'name=CentOS-$releasever - cr\n'
 'baseurl=http://mirror.centos.org/centos/8/cr/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[debuginfo]\n'
 'name=CentOS-$releasever - Debuginfo\n'
 'baseurl=http://debuginfo.centos.org/8/$basearch/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[extras]\n'
 'name=CentOS-$releasever - Extras\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=extras&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/extras/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=1\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[fasttrack]\n'
 'name=CentOS-$releasever - fasttrack\n'
 'mirrorlist=http://mirrorlist.centos.org/?release=8&arch=$basearch&repo=fasttrack&infra=$infra\n'
 '#baseurl=http://mirror.centos.org/centos/$releasever/fasttrack/$basearch/os/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[baseos-source]\n'
 'name=CentOS-$releasever - BaseOS Sources\n'
 'baseurl=http://vault.centos.org/centos/8/BaseOS/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[appstream-source]\n'
 'name=CentOS-$releasever - AppStream Sources\n'
 'baseurl=http://vault.centos.org/centos/8/AppStream/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[powertools-source]\n'
 'name=CentOS-$releasever - PowerTools Sources\n'
 'baseurl=http://vault.centos.org/centos/8/PowerTools/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[extras-source]\n'
 'name=CentOS-$releasever - Extras Sources\n'
 'baseurl=http://vault.centos.org/centos/8/extras/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '[splus-source]\n'
 'name=CentOS-$releasever - Plus Sources\n'
 'baseurl=http://vault.centos.org/centos/8/centosplus/Source/\n'
 'gpgcheck=1\n'
 'enabled=0\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official\n'
 '\n'
 '\n'
 '[epel]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'gpgkey=file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-8\n'
 'gpgcheck=1\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-testing]\n'
 'name=Extra Packages for Enterprise Linux $releasever - Testing - $basearch\n'
 'enabled=0\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=testing-epel8&arch=$basearch\n'
 'failovermethod=priority\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[local]\n'
 'name=local\n'
 'baseurl=https://kojipkgs.fedoraproject.org/repos/epel8-build/latest/$basearch/\n'
 'cost=2000\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-debuginfo]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch - Debug\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-debug-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-source]\n'
 'name=Extra Packages for Enterprise Linux $releasever - $basearch - Source\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-source-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular]\n'
 'name=Extra Packages for Enterprise Linux Modular $releasever - $basearch\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-modular-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular-debuginfo]\n'
 'name=Extra Packages for Enterprise Linux Modular $releasever - $basearch - '
 'Debug\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-modular-debug-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n'
 '\n'
 '[epel-modular-source]\n'
 'name=Extra Packages for Enterprise Linux Modular $releasever - $basearch - '
 'Source\n'
 'mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=epel-modular-source-8&arch=$basearch\n'
 'failovermethod=priority\n'
 'enabled=0\n'
 'skip_if_unavailable=False\n')
config_opts['enable_disable_repos'] = []
config_opts['extra_chroot_dirs'] = ['/run/lock']
config_opts['files'] = {'etc/hosts': '127.0.0.1 localhost localhost.localdomain\n'
              '::1       localhost localhost.localdomain localhost6 '
              'localhost6.localdomain6\n'}
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['macros'] = {'%_buildhost': 'carbon.local',
 '%_platform_multiplier': 1,
 '%_rpmfilename': '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm',
 '%_topdir': '/builddir/build'}
config_opts['nosync'] = True
config_opts['nosync_force'] = True
config_opts['nspawn_args'] = ['--capability=cap_ipc_lock',
 '--bind=/tmp/mock-resolv.1mpmhdbq:/etc/resolv.conf',
 '--bind=/dev/btrfs-control',
 '--bind=/dev/loop-control',
 '--bind=/dev/loop0',
 '--bind=/dev/loop1',
 '--bind=/dev/loop2',
 '--bind=/dev/loop3',
 '--bind=/dev/loop4',
 '--bind=/dev/loop5',
 '--bind=/dev/loop6',
 '--bind=/dev/loop7',
 '--bind=/dev/loop8',
 '--bind=/dev/loop9',
 '--bind=/dev/loop10',
 '--bind=/dev/loop11']
config_opts['plugin_conf'] = {'bind_mount_enable': True,
 'bind_mount_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-8-x86_64',
                     'create_dirs': False,
                     'dirs': [],
                     'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                     'root': 'epel-8-x86_64'},
 'ccache_enable': False,
 'ccache_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-8-x86_64',
                 'compress': True,
                 'dir': '/var/cache/mock/epel-8-x86_64/ccache/u1000/',
                 'max_cache_size': '4G',
                 'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                 'root': 'epel-8-x86_64'},
 'chroot_scan_enable': False,
 'chroot_scan_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                      'cache_topdir': '/var/cache/mock',
                      'cachedir': '/var/cache/mock/epel-8-x86_64',
                      'only_failed': True,
                      'regexes': ['^[^k]?core(\\.\\d+)?$', '\\.log$'],
                      'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                      'root': 'epel-8-x86_64'},
 'compress_logs_enable': False,
 'compress_logs_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-8-x86_64',
                        'command': 'gzip',
                        'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                        'root': 'epel-8-x86_64'},
 'hw_info_enable': True,
 'hw_info_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-8-x86_64',
                  'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                  'root': 'epel-8-x86_64'},
 'lvm_root_enable': False,
 'lvm_root_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                   'cache_topdir': '/var/cache/mock',
                   'cachedir': '/var/cache/mock/epel-8-x86_64',
                   'pool_name': 'mockbuild',
                   'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                   'root': 'epel-8-x86_64'},
 'mount_enable': True,
 'mount_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-8-x86_64',
                'dirs': [],
                'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                'root': 'epel-8-x86_64'},
 'overlayfs_enable': False,
 'overlayfs_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-8-x86_64',
                    'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                    'root': 'epel-8-x86_64'},
 'package_state_enable': True,
 'package_state_opts': {'available_pkgs': False,
                        'basedir': '/var/lib/mock/epel-8-x86_64',
                        'cache_topdir': '/var/cache/mock',
                        'cachedir': '/var/cache/mock/epel-8-x86_64',
                        'installed_pkgs': True,
                        'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                        'root': 'epel-8-x86_64'},
 'pm_request_enable': False,
 'pm_request_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-8-x86_64',
                     'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                     'root': 'epel-8-x86_64'},
 'procenv_enable': False,
 'procenv_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-8-x86_64',
                  'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                  'root': 'epel-8-x86_64'},
 'root_cache_enable': True,
 'root_cache_opts': {'age_check': True,
                     'basedir': '/var/lib/mock/epel-8-x86_64',
                     'cache_topdir': '/var/cache/mock',
                     'cachedir': '/var/cache/mock/epel-8-x86_64',
                     'compress_program': 'lzop',
                     'decompress_program': None,
                     'dir': '/var/cache/mock/epel-8-x86_64/root_cache/',
                     'exclude_dirs': ['./proc',
                                      './sys',
                                      './dev',
                                      './tmp/ccache',
                                      './var/cache/yum',
                                      './var/cache/dnf',
                                      './var/log'],
                     'extension': '.lzo',
                     'max_age_days': 15,
                     'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                     'root': 'epel-8-x86_64',
                     'tar': 'gnutar'},
 'rpkg_preprocessor_enable': False,
 'rpkg_preprocessor_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                            'cache_topdir': '/var/cache/mock',
                            'cachedir': '/var/cache/mock/epel-8-x86_64',
                            'cmd': '/usr/bin/preproc-rpmspec %(source_spec)s '
                                   '--output %(target_spec)s',
                            'requires': ['preproc-rpmspec'],
                            'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                            'root': 'epel-8-x86_64'},
 'selinux_enable': True,
 'selinux_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                  'cache_topdir': '/var/cache/mock',
                  'cachedir': '/var/cache/mock/epel-8-x86_64',
                  'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                  'root': 'epel-8-x86_64'},
 'showrc_enable': False,
 'showrc_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                 'cache_topdir': '/var/cache/mock',
                 'cachedir': '/var/cache/mock/epel-8-x86_64',
                 'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                 'root': 'epel-8-x86_64'},
 'sign_enable': False,
 'sign_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
               'cache_topdir': '/var/cache/mock',
               'cachedir': '/var/cache/mock/epel-8-x86_64',
               'cmd': 'rpmsign',
               'opts': '--addsign %(rpms)s',
               'resultdir': '/var/lib/mock/epel-8-x86_64/result',
               'root': 'epel-8-x86_64'},
 'tmpfs_enable': False,
 'tmpfs_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                'cache_topdir': '/var/cache/mock',
                'cachedir': '/var/cache/mock/epel-8-x86_64',
                'keep_mounted': False,
                'max_fs_size': None,
                'mode': '0755',
                'required_ram_mb': 900,
                'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                'root': 'epel-8-x86_64'},
 'yum_cache_enable': True,
 'yum_cache_opts': {'basedir': '/var/lib/mock/epel-8-x86_64',
                    'cache_topdir': '/var/cache/mock',
                    'cachedir': '/var/cache/mock/epel-8-x86_64',
                    'max_age_days': 30,
                    'max_metadata_age_days': 30,
                    'online': True,
                    'resultdir': '/var/lib/mock/epel-8-x86_64/result',
                    'root': 'epel-8-x86_64'}}
config_opts['print_main_output'] = True
config_opts['releasever'] = '8'
config_opts['root'] = 'epel-8-x86_64'
config_opts['root_log_fmt_str'] = '%(levelname)s %(filename)s:%(lineno)d:  %(message)s'
config_opts['rpmbuild_arch'] = 'x86_64'
config_opts['state_log_fmt_str'] = '%(asctime)s - %(message)s'
config_opts['target_arch'] = 'x86_64'
config_opts['verbose'] = 1
```

</details>

**Comment by hroncok** [comment]
Indeed, when I uninstall pip from the host, it no longer installs anything:

```
ERROR: Pip3 install failed
```

Since mock installs pip to the bootstrap chroot, I suppose that this is a bug.

**Comment by praiskup** [comment]
@hroncok thank you for the report!  There's #771 which could (partly) help with the deps installation.   Though I still see:

    ModuleNotFoundError: No module named 'pytest_httpbin'

While when I switch into the chroot, and run the python3 command manually, I can import that module just fine:

    <mock-chroot> sh-4.4# python3
    Python 3.6.8 (default, Mar 19 2021, 05:13:41) 
    [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pytest_httpbin

IOW, now it installs into /usr/local/lib/python3.6/site-packages -> but the build doesn't seem to read this
location :-/ what would be the correct way to fix this from Python perspective?

**Comment by hroncok** [comment]
When `$RPM_BUILD_ROOT` is set, Python installs packages to `/usr/lib...` and does not see packages in `/usr/local/lib...`.
When `$RPM_BUILD_ROOT` is not set, Python installs packages to `/usr/local/lib...` and it also sees packages in `/usr/lib...`.

Hence, set `$RPM_BUILD_ROOT` to the build root relative to pip's invocation (i.e. most likely `RPM_BUILD_ROOT=/`) when installing the package.

**Comment by praiskup** [comment]
If I got you right, some of the files in /usr/bin,  /usr/lib, etc. will be installed (and owned) by RPM, and some will be installed by PIP, may they mismatch for any reason (pip trying to overwrite what was before written by RPM, etc.)?

**Comment by hroncok** [comment]
Of course, they can, that's why you should never do this in the first place, by installing packages with pip into the buildroot, you lose all integrity and compatibility guarantees.

**Comment by praiskup** [comment]
So isn't there a way to tell python to use both (/usr/local and /usr/lib/...) locations, instead of possibly instructing pip to fight with RPM?

**Comment by praiskup** [comment]
(I don't want to experiment with $RPM_BUILD_ROOT undefined at build-time)

**Comment by xsuchy** [comment]
> When $RPM_BUILD_ROOT is set, Python installs packages to /usr/lib... and does not see packages in /usr/local/lib....

?? Why? I would expect to see both and just prioritize them in some way.

**Comment by praiskup** [comment]
I suppose this is needed when packages are built locally (without mock).  It is the safe default.  But in mock, we could turn this safety measure off, I think.

**Comment by hroncok** [comment]
> Why? I would expect to see both and just prioritize them in some way.

See https://fedoraproject.org/wiki/Changes/Making_sudo_pip_safe and https://discuss.python.org/t/graceful-cooperation-between-external-and-python-package-managers-pep-668/10302/10

**Comment by hroncok** [comment]
> So isn't there a way to tell python to use both (/usr/local and /usr/lib/...) locations, instead of possibly instructing pip to fight with RPM?

You could set PYTHONPATH to the dirs in local, but that could break some spec files that redefine it.

**Comment by praiskup** [comment]
Ok, FTR, this seems to be the downstream patch reacting on RPM_BUILD_ROOT variable: 
https://src.fedoraproject.org/rpms/python3.9/blob/9d73093ec328195ccc8261e72b5e73180c838755/f/00251-change-user-install-location.patch#_1-62

> You could set PYTHONPATH to the dirs in local, but that could break some spec files that redefine it.

Yes, such packages would have to modify PYTHONPATH if already set, instead of blindly replacing it. :-/

Could we add another knob into that condition (in the patch above), so e.g. python would reflect
the /usr/local variable automatically, if some say ` MOCK_EXTERNAL_DEPS`  variable was set?

**Comment by hroncok** [comment]
We could but that's way too specific. I'd prefer to name it more generally, e.g. PYTHON_INLCUDE_USR_LOCAL_FOLDERS_IN_RPM_BUILD_I_KNOW_WHAT_I_AM_DOING

**Comment by hroncok** [comment]
Anyway, a proper way to propose this would be on https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/ -- others might have different opinions.

**Comment by praiskup** [comment]
ACK, makes sense.  In Mock we could also allow both variants btw. (/usr/lib + /usr/local vs. everything in /usr/lib with possible problems).  With a new option (and some default).

For the default (and the initial approach), we should probably go with the "everything in /usr/*" as @hroncok suggested at the beginning.  Then we have at least some chance it will work in all supported chroots, not only the new chroots (supporting the new env-var knob in python).

**Comment by praiskup** [comment]
In PR #771 is an attempt to use `pip install --root  ... --prefix /usr`.  Would that make sense?

**Comment by praiskup** [comment]
I got a different build error now, but I'm not sure if that's problem of the testsuite or the overall approach now:
```
$ mock -r epel-8-x86_64 --config-opts external_buildrequires=True /tmp/httpie/httpie-2.4.0-4.src.rpm
....
==================================== ERRORS ====================================
_____________________ ERROR collecting httpie/__main__.py ______________________
/usr/lib/python3.6/site-packages/py/_path/local.py:686: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('httpie.__main__', '/builddir/build/BUILD/httpie-2.4.0/build/lib/httpie/__main__.py', local('/builddir/build/BUILD/httpie-2.4.0/httpie/__main__.py'))
...
```

**Comment by hroncok** [comment]
Yes, that is a different thing. You can workaround it like this:

```
%check
rm build -rf  # WTF ugly hack to avoid build/lib on sys.path
%pytest -vvv
```

See  https://src.fedoraproject.org/rpms/httpie/pull-request/7#comment-83249

**Comment by praiskup** [comment]
#771  seems to fix this, then.  Thank you for reporting this.
