### ISSUE TITLE
PermissionError is not defined in Python 2.7

### ISSUE THREAD

**Issue by cmolinar** [rpm-software-management/mock#84]
There is no PermissionError in Python 2.7, it was introduced in the Python 3.3 stream with PEP 3151. 

When using the mock-scm plugin with Python 2.7.5 and there's a permission issue, the following stacktrace is produced:

```
ERROR: global name 'PermissionError' is not defined
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 886, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 701, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 720, in run_command
    scmWorker.get_sources()
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/scm.py", line 95, in get_sources
    except PermissionError as e:
NameError: global name 'PermissionError' is not defined
```

Versions involved:

Python 2.7.5
Mock 1.3.4
CentOS 7.3.1611

My current fix for this is to include:

`class PermissionError(Exception): pass`

at the top of scm.py.

**Comment by xsuchy** [comment]
Hopefully fixed. But I will have no access to EL7 till Monday. Can you please test version from https://copr.fedorainfracloud.org/coprs/g/mock/mock/ ? Does it work for you?

**Comment by cmolinar** [comment]
That 46596df build works, thank you!
(that copr interface is so much nicer than koji's 👍 )
