### ISSUE TITLE
The --noclean option is not on RHEL6, so cleanup_on_success=False breaks EL6

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/mock#953]
Forward from: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-4e4f7442dc

```
Update unfortunately breaks building packages for RHEL 6…

Mock Version: 3.1
ENTER ['do_with_status'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --noclean --target x86_64 --nodeps /builddir/build/SPECS/example.spec'], chrootPath='/var/lib/mock/centos+epel-6-x86_64-example/root'env={'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'}shell=Falselogger=<mockbuild.trace_decorator.getLog object at 0x7f714f793ba8>timeout=0uid=1000gid=135user='mockbuild'nspawn_args=[]unshare_net=TrueprintOutput=False)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --noclean --target x86_64 --nodeps /builddir/build/SPECS/example.spec'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8'} and shell False
--noclean: unknown option
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mockbuild/[trace_decorator.py](http://trace_decorator.py/)", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/[util.py](http://util.py/)", line 598, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bs --noclean --target x86_64 --nodeps /builddir/build/SPECS/example.spec
```

Work-around is to not use `cleanup_on_success = False` for now.

**Comment by praiskup** [comment]
https://github.com/rpm-software-management/mock/blob/9bf3cb57e4a14cdce4fb85d989171d5d48d5a6ef/mock/py/mockbuild/config.py#L521-L523

"cleanup_on_success=False" is enforced :-( so the workaround doesn't work
